[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Force HTTPS redirects
[[redirects]]
  from = "http://causafoundation.com/*"
  to = "https://causafoundation.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.causafoundation.com/*"
  to = "https://causafoundation.com/:splat"
  status = 301
  force = true

# Handle Next.js static assets
[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Handle all other routes (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers with HTTPS enforcement
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
